### ISSUE TITLE
Council web site is producing 5xx error

### ISSUE THREAD

**Issue by LoveMyData** [LoveMyData/wollondilly#1]
```
/app/vendor/bundle/ruby/2.0.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:323:in `fetch': 502 => Net::HTTPBadGateway for https://ecouncil.wollondilly.nsw.gov.au/eServeDAEnq.htm -- unhandled response (Mechanize::ResponseCodeError)
 	from /app/vendor/bundle/ruby/2.0.0/gems/mechanize-2.7.5/lib/mechanize.rb:464:in `get'
 	from scraper.rb:26:in `<main>'
```

Hi council

I am trying to search for DA on your web site and keep getting error, can you please check?

http://www.wollondilly.nsw.gov.au/planning-and-development/da-tracker/

Many Thanks
Eric

**Comment by LoveMyData** [comment]
Dear Eric,
 
We are currently experiencing problems with the DA Tracker and hope to have online soon.
 
Is there any particular DA you are trying to locate information on?
 
Regards,

**Comment by LoveMyData** [comment]
council fixed their web site, tested scraper and all running fine again.
